### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [kauefontes/quewui.theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by kauefontes** [comment]
Thanks, I just did it and i think now is good to go. Thank you, budy!

**Comment by unixorn** [comment]
Thanks, adding it.
